steps:

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'stocker', '.']
    dir: 'cloudcode/stocker/src'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['run', '--name', 'stocker-test', '--network', 'cloudbuild', '-p', '5000', '-d', 'stocker']
  - name: 'qnib/pytest'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      pip install -r requirements.txt
      cd cloudcode/stocker/tests
      pytest -s ./
    env:
      - 'HOGE=fuga'

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - functions
    - deploy
    - stocker-daily
    - --region           = asia-northeast1
    - --entry-point      = __main__
    - --ignore-file      = .gitignore, cloudbuild.yaml
    - --ingress-settings = internal-only
    - --memory           = 256MB
    - --runtime          = python38
